apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soneta.fullname.server" . }}
  labels:
{{ include "soneta.labels.server" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "soneta.labels.server" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "soneta.labels.server" . | indent 8 }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-server-{{ .Values.image.product}}"
          image: "{{ .Values.image.repository }}soneta/server.{{ .Values.image.product}}:{{ .Values.image.tag }}{{ include "soneta.server.tagPostfix" . }}"
          imagePullPolicy: IfNotPresent
          command: {{ include "soneta.server.command" . }}
          args: {{ include "soneta.server.args" . }}
          ports:
            - name: {{ .Values.service.server.port0Name }}
              containerPort: {{ .Values.service.server.port0 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.server | nindent 12 }}
          env:
            {{- if .Values.envs.server }}
            {{- toYaml .Values.envs.server | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.resources.pvc.enabled }}
            - name: pvc-volume
              mountPath: {{ .Values.resources.pvc.mountPath | quote }}
            {{- end }}
            {{- if .Values.resources.smb.enabled }}
            - name: smb-volume
              mountPath: {{ .Values.resources.smb.mountPath | quote }}
            {{- end }}
            {{- if .Values.resources.afs.enabled }}
            - name: afs-volume
              mountPath: {{ .Values.resources.afs.mountPath | quote }}
            {{- end }}
            {{- if .Values.listaBazDanych }}
            - name: lista-baz-danych-volume
              mountPath: "/config"
            {{- end }}
      volumes:
        {{- if .Values.resources.pvc.enabled }}
        - name: pvc-volume
          persistentVolumeClaim:
            claimName: {{ include "soneta.fullname.server" . }}
        {{- end }}
        {{- if .Values.resources.smb.enabled }}
        - name: smb-volume
          persistentVolumeClaim:
            claimName: {{ include "soneta.fullname.pvc" . }}
        {{- end }}
        {{- if .Values.resources.afs.enabled }}
        - name: afs-volume
          azureFile:
            secretName: {{ include "soneta.fullname.server" . }}
            shareName: {{ required "Azure storage share name is required" .Values.resources.afs.shareName | quote }}
            readOnly: false
        {{- end }}
        {{- if .Values.listaBazDanych }}
        - name: lista-baz-danych-volume
          configMap:
            name: {{ include "soneta.fullname.server" . }}
            items:
            - key: lista-baz-danych
              path: "lista-baz-danych.xml"
        {{- end }}
      nodeSelector:
        kubernetes.io/os: {{ include "soneta.server.nodeselector.os" . }}
      {{- with .Values.nodeSelector }}
          {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
