{{- if .Values.ingress.enabled -}}
{{- $fullName := include "soneta.fullname.web" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "soneta.labels.web" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
      - {{ $releaseName }}.{{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
  rules:
    - host: {{ $releaseName }}.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          {{- if .Values.image.webapi }}
          - path: /api/
            backend:
              serviceName: {{ include "soneta.fullname.webapi" . }}
              servicePort: http
          {{- end -}}
          {{- if .Values.image.webwcf }}
          - path: /Business/
            backend:
              serviceName: {{ include "soneta.fullname.webwcf" . }}
              servicePort: http
          {{- end -}}
{{- end }}
