{{- if not (include "soneta.isOrchestrator" .) -}}
{{- $component := (list . "server") -}}
{{ include "soneta.service" $component }}
---
{{ include "soneta.service" (list . "server" "commhub" 8082) }}
{{- end -}}