{{- if .Values.resources.smb.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "soneta.fullname.pvc" . }}
spec:
  storageClassName: ""
  volumeName: {{ include "soneta.fullname.pv" . }}
  resources:
    requests:
      storage: {{ .Values.resources.smb.requests }}
  accessModes:
    - ReadWriteMany
{{- end }}