{{- if .Values.resources.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "soneta.fullname.server" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "soneta.resources.pvc.storageClassName" . }}
  resources:
    requests:
      storage: {{ .Values.resources.pvc.requests }}
{{- end }}